name: ds311
channels:
  - conda-forge
dependencies:
  - anyio=4.11.0
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - astroid=3.3.11
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - autopep8=2.0.4
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - black=25.1.0
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - docstring-to-markdown=0.17
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - flake8=7.1.2
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - gflags=2.2.2
  - glog=0.7.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - isort=6.1.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupytext=1.18.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpng=1.6.51
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mccabe=0.7.0
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - mistune=3.1.4
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nbstripout=0.8.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pathspec=0.12.1
  - patsy=1.0.2
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - platformdirs=4.5.0
  - pluggy=1.6.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.19.2
  - pylint=3.3.9
  - pyobjc-core=12.1
  - pyobjc-framework-cocoa=12.1
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-lsp-server=1.13.2
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - re2=2025.11.05
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rope=1.14.0
  - rpds-py=0.29.0
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - terminado=0.18.1
  - tk=8.6.13
  - tomli=2.3.0
  - tomlkit=0.13.3
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ujson=5.11.0
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - whatthepatch=1.0.7
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yapf=0.43.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - pytoolconfig==1.3.1
      - tinycss2==1.4.0
